apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-23qb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-23qb@sha256:5808856a3fcd718eb9e253b49c7e4fd04dd02fba8807e8d79003681bc001d3ea
        name: my-python
        resources: {}
status: {}
